# Server Configuration
server.port=8080
server.servlet.context-path=/api

# MongoDB Configuration 
# මම මේක ඔයා දුන්න Atlas link එකටම හැදුවා
spring.data.mongodb.uri=mongodb+srv://smartcampushub:smartcampus_hub@cluster0.0yi3gfw.mongodb.net/SmartCampusDB?retryWrites=true&w=majority

# Logging Configuration
logging.level.root=INFO
logging.level.com.smartcampus.hub=DEBUG

# OAuth2 Google Configuration
# පස්සේ ඇත්තම ID/Secret හම්බුණාම මේවා replace කරන්න. දැනට error එක එන එක නවත්තන්න මම මේවා dummy values දැම්මා.
spring.security.oauth2.client.registration.google.client-id=194337731331-kv55hq4n86bln9honk84e7ida235o02f.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
app.google.client-id=${spring.security.oauth2.client.registration.google.client-id}

# JWT Configuration
# Variable එක වෙනුවට කෙලින්ම Secret key එක මෙතනට දැම්මා
app.jwt.secret=SmartCampusSuperSecretKey2026VihangaPAFProject
app.jwt.expiration=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

# CORS Configuration
app.cors.allowed-origins=http://localhost:3000,http://localhost:3001,http://localhost:5173